[package]
name = "rust_sdstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.10"
simplelog = { version = "^0.12.0", features = ["paris"] }